### ISSUE TITLE
Can't scroll up in Project Settings

### ISSUE THREAD

**Issue by matkovsky** [bdkjones/CodeKit2#4]
While just clicking through the options that's what's happend. I cannot scroll up properly on some setting pages since.

![screenshot 2013-12-18 12 01 13](https://f.cloud.github.com/assets/1693178/1772609/2de9093c-67d4-11e3-94e0-3a59f521c906.png)
![screenshot 2013-12-18 12 01 25](https://f.cloud.github.com/assets/1693178/1772610/2df61a14-67d4-11e3-9e68-4f455b2ec328.png)

**Comment by bdkjones** [comment]
Handy. Quitting and restarting the app should solve this. See if you can reliably reproduce it, please. If so, please add all the information about your system you can give me to this issue.

**Comment by matkovsky** [comment]
Nope, relaunching didn't help. I even tried to add a different project after Shift+relaunching CodeKit. Same problem.

I'm using OS X 10.8.5 on a MBP 15" Early 2011, and a classic mouse with a wheel, not a Magic one. Hope this helps. :pray:

**Comment by bdkjones** [comment]
Interesting. It may be related to 10.8. I only have 10.9 over here right now. Do you have access to a second Mac you can test on?

**Comment by matkovsky** [comment]
Yes, later today I'll test it on a Mac mini running Mavericks. Thanks!

**Comment by tiagofranco** [comment]
I'm also facing the same problem. Running latest Mavericks, 10.9.1, on a Macbook Pro, using classic 3 button mouse with scroll wheel. Shift-Click restart didn't solve it.

![screenshot 2013-12-19 02 44 46](https://f.cloud.github.com/assets/623377/1779811/9bd4f896-6858-11e3-9c2a-42245c1fceaa.png)

Then, after scrolling down...

![screenshot 2013-12-19 02 44 58](https://f.cloud.github.com/assets/623377/1779813/abe9a70e-6858-11e3-82a2-75d71a5ecb1a.png)

I was unable to scroll up more that this.

Also, other items seemed to have too much blank space on top, seems to be related:

![screenshot 2013-12-19 02 54 52](https://f.cloud.github.com/assets/623377/1779821/ffe2f248-6858-11e3-8a9f-2b8683a22860.png)

I think, though I might be wrong, it as something to do with selecting an item on the left sidebar and scrolling down, then going back to an item that doesn't need scrolling to see all its contents. I can't reproduce it, sorry.

**Comment by matkovsky** [comment]
Yes! I have tested it on a Mac mini with Mavericks. It works perfectly when there are no scrollbars displayed, however when I turn on scroll bars in System Preferences, this bug reappears.

**Comment by tiagofranco** [comment]
Yes, I should probably get that clear: scrollbars are always on for me too.

**Comment by BabylonSix** [comment]
Scrolling bug I noticed under 10.9.1
If you select either the language defaults, or less, or sass (under language defaults)
and then choose stylus or slim (right after the previous action)
then you wont be able to scroll, if you however resize the window - the options are still there, they just wont scroll with a small window.

I played around with all the Language Defaults languages choices, and those are the only ones that seem to exhibit that behavior, and only in that order for some reason, if you click on any other language option and then back to slim or stylus, they work just fine.

**Comment by bdkjones** [comment]
Ah. I see. This bug only manifests if you have scrollbars set to "always" display.

I'll have to take a look.

**Comment by BabylonSix** [comment]
I somehow closed the issue? what?

**Comment by BabylonSix** [comment]
Using OS X 10.9.1
Playing around with it some more (my scroll bars are set to always hidden by the way)
Application is resized to the smallest possible size (vertically)

1# Language Defaults Bug
click between Language Defaults > JavaScript > Language Defaults > Javascript
now you can't scroll the view for Javascript, works the same with every other language choice. Try it.

2# Less and Sass bug
click Less or Sass from the Language Defaults > Any language other than Less, Sass, and Typescript
again, can't scroll.

With both bugs, if you resize the app to be taller, the options are still there.

**Comment by bdkjones** [comment]
Fixed. 

Issue will be resolved in Beta 3, which I will post soon-ish.
